version: "3.9"
services:
  car-kit:
    image: postgres:alpine
    container_name: car-kit
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=car-kit
    volumes:
      - storage:/tukitoki/car-kitdb
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - car-kit
    environment:
      - DB_URL=jdbc:postgresql://car-kit:5432/car-kit
      - DB_USER=postgres
      - DB_PASS=postgres
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  storage: