version: "3.9"
services:
  car_kit:
    image: postgres:alpine
    container_name: car_kit
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=car_kit
    volumes:
      - storage:/tukitoki/car_kitdb
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - car_kit
    environment:
      - DB_URL=jdbc:postgresql://car_kit:5432/car_kit
      - DB_USER=postgres
      - DB_PASS=postgres
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  storage: