spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/car_kit}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:RasP91AS}
  jpa:
    hibernate:
      ddl-auto: update

repair-shop:
  startTimeWork: "08:00"
  endTimeWork: "19:00"

jwt:
  secret-key: ${PRIVATE_KEY:fe1501ba654b1adfaf05cc4195680bd04d6aa2afea771b30e9db3956cc411324}
  access-validity: 3600000
  refresh-validity: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs